---
title: 運用tmap將iTW資料視覺化
date: "`r Sys.time()`"
output:
  html_document:
    highlight: pygments
    theme: flatly
    css: ../style.css
---
<hr>
```{r}
pacman::p_load(readr, dplyr, sf, tmap, stringr)
```
<hr>

**認識tmap**</p>
tmap：將空間數據視覺化的地圖繪製套件，可以用類似ggplot的方式繪製地圖</p>
須將資料利用sf轉換之後才能使用tmap繪製地圖</p>
<br>
<hr>

###載入資料與整理
```{r}
# 台灣人口統計資料
load("K.RData")
load("twTown.RData")
```
<br>
```{r}
# 選取高雄市的資料
K = subset(twVill, COUNTY=="高雄市")
```
<br>
```{r}
i = c("鼓山區","鹽埕區","左營區","新興區","前鎮區","苓雅區","前金區","三民區")
K= subset(K, TOWN %in% i)
TOWN = subset(twTown, TOWN %in% i)
```
<br>
```{r}
# 高雄捷運輕軌資料
L = st_read("kaoh/light_rail/LRT_1090102.shp", crs=3826)
L = subset(L,LRTSYS=="高雄捷運")
st_crs(L) # 檢查座標
# 在台灣一般而言是3826(平的)與4326(球形)，但較常使用3826
L = L %>% mutate_if(is.factor,as.character)
```
<br>
```{r}
# 房產時價登錄資料
load("kaoh/house_price.rdata")
A <- st_as_sf(D, coords=c("E","N"), crs=4326) %>% 
  st_transform(crs=3826)
# 在資料框中加入geometry的資訊
# "E"東經 "N"北緯
# 當資料本身是經緯度時，不能直接轉3826，要先轉4326
```
<br>
```{r}
# 對房屋資料進行抽樣
set.seed(2020) # 固定抽樣結果
A = subset(A, town_name %in% i) %>% sample_n(5000)
```
<br>
```{r}
# 由於每坪價格的極端值影響視覺化效果，故取log
A = A %>% mutate(uprice_log = log(uprice))
```
<hr>
<br>

###tmap畫圖
<p>tmap功能簡介</p>

<ul>
<li>tm_shape() 選取目標圖層</li>
<li>tm_fill() 圖層填滿</li>
<li>tm_borders() 加入邊界</li>
<li>tm_dots() 加入點</li>
<li>tm_lines() 加入線</li>
<li>tm_text() 加入文字</li>
<li>tm_polygon() = tm_fill() + tm_borders()</li>
</ul>
```{r}
# 畫出互動式地圖
tmap_mode("view")
tm_shape(K,name="人口密度")+
  tm_polygons("P_DEN", palette = "Greens", title="人口密度", alpha=0.5)+
tm_shape(K,name="性別比")+
  tm_polygons("M_F_RAT", palette = "Blues", title="性別比", alpha=0.5)+
tm_shape(K,name="平均收入")+
  tm_polygons("I_AVG", palette = "Reds", title="平均收入", alpha=0.5, n=8)+
tm_shape(K,name="老化指數")+
  tm_polygons("FLD4", palette = "PuRd", title="老化指數", alpha=0.5, n=8)+
tm_shape(K,name="教育程度")+
  tm_polygons("EDU_RAT", palette = "YlOrBr", title="教育程度", alpha=0.5, n=8)+
tm_shape(K,name="里名") + tm_borders(col="gray") +
  tm_text(text="VILLAGE",col="black",size=0.5)+
tm_shape(TOWN,name="區名") + tm_borders(col="black", lwd=2) +
  tm_text(text="TOWN",col="navy",size=1)+
tm_shape(L,name="輕軌路線")+
  tm_lines(col='LRTID', lwd=3, palette=c("green","orange"))+
tm_shape(A,name="每坪價格")+
  tm_dots(col='uprice_log', size=0.01, alpha=0.9 ,n=8, title="每坪價格", palette = "GnBu")+
tm_shape(A,name="房屋用途")+
  tm_dots(col='usage', size=0.01, alpha=0.9 ,n=5, title="房屋用途", palette = "Set1")+
tm_shape(A,name="屋齡")+
  tm_dots(col='age', size=0.01, alpha=0.9 ,n=5, title="屋齡", palette = "Paired")
```


